"""
Django settings for yaser project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')2f9g2(g2l%q-2&bcph33@22ooiil32^csw5qs@*9jmj)3fgwk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    #'django_admin_bootstrapped',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites', #gia to registration-redux
    'registration', #redux django registration  prepei na mpei akrivws apo katw
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'seminar',
    'userprofile',
    'notifications',
    #THIRD PARTY APPS
   # 'django-model-utils'
    'crispy_forms',
    'bootstrap3',
    'django_extensions',
    'admin_honeypot',
    'django_filters',
    'imagekit'

   # 'geoposition'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'yaser.urls'



# auto den uparxei meta tin 1.8 ekdosi
#from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP

#TEMPLATE_CONTEXT_PROCESSORS = TCP + (
#    'django.core.context_processors.request',
#)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")], # edw orizw to path pou tha vlepei ta template default []
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yaser.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': '/Users/tns/Desktop/yaseminar1/yaser/storage.db',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Athens'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')     giati eimate se developing mode k prepei na valw to debug mode opws apo katw, episis na allaxtoun sto urls.py
if DEBUG:
    
    STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static", "static-only")
    MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media")      # grafete k etsi"/Users/tns/Desktop/yaseminar32/static/media"
    STATICFILES_DIRS = (
        os.path.join(os.path.dirname(BASE_DIR), "static", "static"),
    )


#print "base dir path", BASE_DIR    gia na dw poio einai to base dir
#STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root") #egw to prosthesa dokimastika




#Crispy FORM TAGs SETTINGS
CRISPY_TEMPLATE_PACK = 'bootstrap3'

#EMAIL !!!!!!!!!!!!!
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
EMAIL_FILE_PATH = os.path.join(os.path.dirname(BASE_DIR), "email_test") # change this to a proper location

#REGISTRATION EDW VAZW TA STOIEIA APO TO REGISTRATION APP POU KATEVASA TO  REDUX
ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True #if they activate to be able to log-in
REGISTRATION_EMAIL_HTML = False
SITE_ID=5 #'django.contrib.sites', #gia to registration-redux
LOGIN_REDIRECT_URL = '/'
#REGISTRATION_FORM = 'userprofile.forms.customform' #GIA NA EPEKTINW TIS LEITOURGIES TOU REGISTRATION-REDUX

SITE_URL = '127.0.0.1:8000/'
#GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyDA6SGvpEg8kuyrlwJ8BdoIO8yIJIZapcc'


